"""empty message

Revision ID: 44c363d4c855
Revises: 6531e49737b3
Create Date: 2022-03-18 01:41:36.808759

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c363d4c855'
down_revision = '6531e49737b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('nba_id', sa.Integer(), nullable=True))
    op.add_column('player', sa.Column('jersey', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'player', ['nba_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'player', type_='unique')
    op.drop_column('player', 'jersey')
    op.drop_column('player', 'nba_id')
    # ### end Alembic commands ###
