"""empty message

Revision ID: 52d79840d7e3
Revises: 44c363d4c855
Create Date: 2022-03-18 02:08:24.777306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52d79840d7e3'
down_revision = '44c363d4c855'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'year')
    # ### end Alembic commands ###
