"""empty message

Revision ID: 617bded22462
Revises: daae1d0245d8
Create Date: 2022-03-21 22:11:13.293750

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '617bded22462'
down_revision = 'daae1d0245d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stats', sa.Column('bpg', sa.String(length=50), nullable=True))
    op.add_column('stats', sa.Column('tpg', sa.String(length=50), nullable=True))
    op.add_column('stats', sa.Column('pf', sa.String(length=50), nullable=True))
    op.add_column('stats', sa.Column('fgpct', sa.String(length=50), nullable=True))
    op.add_column('stats', sa.Column('fgtpct', sa.String(length=50), nullable=True))
    op.add_column('stats', sa.Column('ftpct', sa.String(length=50), nullable=True))
    op.add_column('stats', sa.Column('games', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stats', 'games')
    op.drop_column('stats', 'ftpct')
    op.drop_column('stats', 'fgtpct')
    op.drop_column('stats', 'fgpct')
    op.drop_column('stats', 'pf')
    op.drop_column('stats', 'tpg')
    op.drop_column('stats', 'bpg')
    # ### end Alembic commands ###
