"""empty message

Revision ID: 716a043decd8
Revises: 7132bece1d1e
Create Date: 2022-03-20 01:21:56.761964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '716a043decd8'
down_revision = '7132bece1d1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('team_pic', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'team_pic')
    # ### end Alembic commands ###
