"""empty message

Revision ID: 77d78954e63c
Revises: 52d79840d7e3
Create Date: 2022-03-18 02:59:43.828176

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d78954e63c'
down_revision = '52d79840d7e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('player', 'pic')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('player', sa.Column('pic', sa.VARCHAR(length=250), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
