"""empty message

Revision ID: 853d7f6ccd76
Revises: 716a043decd8
Create Date: 2022-03-20 23:12:10.743556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '853d7f6ccd76'
down_revision = '716a043decd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stats',
    sa.Column('stat_id', sa.Integer(), nullable=False),
    sa.Column('main_id', sa.Integer(), nullable=True),
    sa.Column('season', sa.Integer(), nullable=True),
    sa.Column('ppg', sa.String(length=20), nullable=True),
    sa.Column('rpg', sa.String(length=20), nullable=True),
    sa.Column('apg', sa.String(length=250), nullable=True),
    sa.Column('mpg', sa.String(length=50), nullable=True),
    sa.Column('spg', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('stat_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats')
    # ### end Alembic commands ###
